In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
def hopefield_train(X):
    num_samples, num_features = X.shape

    # Initialize weights matrix
    weights = np.zeros((num_features, num_features))

    # Update weights based on training data
    for i in range(num_samples):
        x = X[i]
        weights += np.outer(x, x)

    # Set diagonal elements to zero to prevent self-connections
    np.fill_diagonal(weights, 0)

    return weights

X = np.array([[1,-1,-1,1],[1,1,1,1],[1,-1,1,-1],[1,-1,-1,-1],[1,1,-1,-1]])
weights = hopefield_train(X)
print(weights)

[[ 0. -1. -1. -1.]
 [-1.  0.  1.  1.]
 [-1.  1.  0.  1.]
 [-1.  1.  1.  0.]]


In [23]:
import numpy as np
from sklearn.model_selection import train_test_split

def hopefield_train(X):
    num_samples, num_features = X.shape

    # Initialize weights matrix
    weights = np.zeros((num_features, num_features))

    # Update weights based on training data
    for i in range(num_samples):
        x = X[i]
        weights += np.outer(x, x)
    '''
    --x = X[i] assigns the current training sample to the variable x.
    --np.outer(x, x) calculates the outer product of the x vector with itself. It results in a matrix of size 
    (num_features, num_features) where each element is the product of the corresponding elements of x.
    --weights += np.outer(x, x) adds the outer product matrix to the weights matrix. This step accumulates the 
    contributions from all training samples to the weights matrix.
    '''
    
    # Set diagonal elements to zero to prevent self-connections
    np.fill_diagonal(weights, 0)

    return weights

def hopefield_predict(X, weights):
    num_samples, num_features = X.shape

    # Perform synchronous update of neurons until convergence
    converged = False
    iteration = 0
    state_history = []  # Store the state of each sample at each iteration
    
    while not converged:
        converged = True
        for i in range(num_samples):
            x = X[i]
            old_x = x.copy()
            
            # Update neuron states based on weighted sum of inputs
            x = np.sign(np.dot(weights, x))
            
            # Check for convergence
            if not np.array_equal(x, old_x):
                converged = False
            X[i] = x
        
        iteration += 1
        state_history.append(X.copy())  # Append the current state to the history
    
    return X, state_history

def compute_accuracy(y_pred, y_true):
    num_samples = len(y_true)
    correct = np.sum(y_pred == y_true)
    accuracy = correct / num_samples * 100
    return accuracy

# Generate a random dataset with 1000 samples and 4 features; binary class classification
X = np.random.randint(0, 2, size=(10000, 4))
y = np.random.randint(2, size=10000)

def hopfield(TEST):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST/100, random_state=42)
    weights = hopefield_train(X_train)
    X_test_pred, state_history = hopefield_predict(X_test, weights)
    y_test_pred = np.sign(np.sum(X_test_pred, axis=1))
    accuracy = compute_accuracy(y_test_pred, y_test)
    print("Accuracy: %.2f%%" % accuracy)
    
    print("Convergence Pattern:")
    for i, states in enumerate(state_history):
        print(f"Iteration {i+1}:")
        print(states)
        print()

hopfield(20)
hopfield(30)
hopfield(40)


Accuracy: 51.65%
Convergence Pattern:
Iteration 1:
[[1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Iteration 2:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Iteration 3:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Accuracy: 50.53%
Convergence Pattern:
Iteration 1:
[[1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 0 1]
 [1 1 1 0]]

Iteration 2:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Iteration 3:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Accuracy: 50.32%
Convergence Pattern:
Iteration 1:
[[1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Iteration 2:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Iteration 3:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

